server:
  port: 8080
logging:
  config: classpath:logback-spring.xml
spring:
  application:
    name: code
  messages:
    basename: i18n/messages  # 关键：指定路径前缀
    encoding: UTF-8
    cache-duration: 3600s
